id: P003129
initial_creation_type: ocr
source_metadata:
  id: bdr:W2CZ5987
  title: བསྟན་འཛིན་རབ་རྒྱས་ཀྱི་རྣམ་ཐར་
  author: ''
  volumes:
    52c0c1e3bf004065ae6a990686259cca:
      image_group_id: I2DB64882
      title: ''
      volume_number: 1
      total_pages: 768
      base_file: v001.txt
