id: ID3819D43
legacy_id: P003129
ocr_import_info:
  bdrc_scan_id: W2CZ5987
  source: bdrc
  ocr_info:
    timestamp: '2020-03-28T10:29:12'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-09-02T14:59:00.250234+00:00'
last_modified: 2022-09-02 23:00:12.149177
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W2CZ5987
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  geo_restriction:
  - CN
  reproduction_of: http://purl.bdrc.io/resource/MW2CZ5987
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: བསྟན་འཛིན་རབ་རྒྱས་ཀྱི་རྣམ་ཐར།
  author: འབྲུག་རྗེ་མཁན་པོ ༠༦་ངག་དབང་ལྷུན་གྲུབ།
statistics:
  ocr_word_mean_confidence_index: 0.5263315465509786
  ocr_word_median_confidence_index: 0.49000000953674316
quality: null
bases:
  I2DB64882:
    source_metadata:
      id: http://purl.bdrc.io/resource/I2DB64882
      total_pages: 768
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I2DB64882.txt
    statistics:
      ocr_word_median_confidence_index: 0.49000000953674316
      ocr_word_mean_confidence_index: 0.5263315465509786
    legacy_id: v001
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
